### ISSUE TITLE
could you share your model files?or how fast is on cpu?

### ISSUE THREAD

**Issue by lyk125** [camel007/caffe2-mobilenet#1]

**Comment by camel007** [comment]
https://pan.baidu.com/s/1mi7Luw4

**Comment by lyk125** [comment]
thanks! But how could I use the .mdl file? the caffe2's model file is .pb

**Comment by camel007** [comment]
Please check  [thisfile](https://github.com/camel007/caffe2-mobilenet/blob/master/mobile_net_trainer.py)
